# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 17:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_reviews", "0001_initial"),
        ("django_reviews", "0002_alter_review_status"),
        ("django_reviews", "0003_productrepresentation_magento_id_and_more"),
        ("django_reviews", "0004_review_is_sent_to_magento"),
        ("django_reviews", "0005_review_name"),
        ("django_reviews", "0006_alter_review_created_at"),
        ("django_reviews", "0007_alter_review_options_alter_review_unique_together"),
    ]

    dependencies = [
        ("django_accounts", "0001_squashed_0032_customer_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=2048, null=True)),
                ("average_rate", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                (
                    "number_of_reviews",
                    models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True),
                ),
                ("magento_id", models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                "verbose_name_plural": "products reviews details",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("not_accepted", "Not Accepted"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("channel_idx", models.CharField(blank=True, max_length=256, null=True)),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
                ("detail", models.CharField(blank=True, max_length=8000, null=True)),
                ("average_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("source", models.CharField(blank=True, max_length=256, null=True)),
                ("is_sent_to_magento", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_accounts.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_products",
                        to="django_reviews.productrepresentation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("product", "customer")},
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate", models.FloatField(blank=True, null=True)),
                ("rating_name", models.CharField(blank=True, max_length=256, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_rate",
                        to="django_reviews.review",
                    ),
                ),
            ],
        ),
    ]
